var g=true,h=null,j=false;function n(d,c){var a=c.parentNode;a.e==c?a.appendChild(d):a.insertBefore(d,c.nextSibling)}function o(d,c){for(var a=[],b=p.getElementsByTagName("*"),e=0;e<b.length;e+=1)b[e].hasAttribute(d)&&b[e].getAttribute(d)==c&&a.push(b[e]);return a}
function aa(d){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(c){q=c;c=j;for(var a=0;a<q.length;a++)if(q[a][0]==d[0]&&q[a][1]==d[1])c=g;if(c)alert(chrome.i18n.getMessage("thread_already_watched",d[1]));else{q.push(d);r();alert(chrome.i18n.getMessage("thread_now_watched",d[1]))}s()})}function ba(d,c){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(a){q=a;for(a=0;a<q.length;a++)q[a][0]==d&&q[a][1]==c&&q.splice(a,1);r();s()})}
function r(){chrome.extension.sendRequest({reqtype:"set-watchedthreads",watchedthreads:q})}function t(d,c,a){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(b){q=b;for(b=0;b<q.length;b++)if(q[b][0]==c&&q[b][1]==a)q[b][4]=d.replace('"',"").replace("<","").replace(">","");r()})}function ca(){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(d){q=d;s()})}
function s(){var d=u.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(d!=h){var c=d[1];watchboxtable=p.getElementById("watchboxtable");watchboxtable.innerHTML='<tr><td class="postblock" style="border-right: 0px none;">No.</td><td class="postblock" style="border-left: 0px none;border-right: 0px none;">'+chrome.i18n.getMessage("subject")+'</td><td class="postblock" style="border-left: 0px none;border-right: 0px none;">'+chrome.i18n.getMessage("author")+'</td><td class="postblock" style="border-left: 0px none;border-right: 0px none;">'+
chrome.i18n.getMessage("note")+'</td><td class="postblock" style="border-left: 0px none;">&nbsp;</td></tr>';d=[];for(var a=0;a<q.length;a++)q[a][0]==c&&d.push(q[a]);if(d.length==0){c=p.createElement("tr");c.innerHTML='<td colspan="5" align="center">'+chrome.i18n.getMessage("no_watched_threads")+"</td>";watchboxtable.appendChild(c)}else for(a=0;a<d.length;a++){c=p.createElement("tr");c.innerHTML='<td style="padding-left: 3px;padding-right: 3px;">'+d[a][1]+'</td><td class="filetitle" style="padding-left: 3px;padding-right: 3px;">'+
d[a][2]+'</td><td class="postername" style="padding-left: 3px;padding-right: 3px;">'+d[a][3]+'</td><td style="padding-left: 3px;padding-right: 3px;"><input type="text" placeholder="'+chrome.i18n.getMessage("enter_a_note")+'" size="12" value="'+d[a][4]+'" id="note'+d[a][0]+d[a][1]+'"></td><td style="padding-left: 3px;padding-right: 3px;"><small>[<a href="/'+d[a][0]+"/res/"+d[a][1]+'">'+chrome.i18n.getMessage("view")+'</a>] [<a href="#" id="delete'+d[a][0]+d[a][1]+'">'+chrome.i18n.getMessage("delete")+
"</a>]</small></td>";watchboxtable.appendChild(c);c=p.getElementById("note"+d[a][0]+d[a][1]);c.setAttribute("board",d[a][0]);c.setAttribute("threadid",d[a][1]);c.onchange=function(){t(this.value,this.getAttribute("board"),this.getAttribute("threadid"))};c.onkeyup=function(){t(this.value,this.getAttribute("board"),this.getAttribute("threadid"))};c=p.getElementById("delete"+d[a][0]+d[a][1]);c.setAttribute("board",d[a][0]);c.setAttribute("threadid",d[a][1]);c.addEventListener("click",function(){w.confirm(chrome.i18n.getMessage("stop_watching_thread",
this.getAttribute("threadid")))&&ba(this.getAttribute("board"),this.getAttribute("threadid"))},j)}}}function da(d){chrome.extension.sendRequest({reqtype:"get-hiddenthreads"},function(c){x=c;c=u.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(c!=h){for(var a=j,b=0;b<x.length;b++)if(x[b][0]==c[1]&&x[b][1]==d)a=g;if(!a){x.push([c[1],d]);y()}}})}
function ea(d){chrome.extension.sendRequest({reqtype:"get-hiddenthreads"},function(c){x=c;c=u.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(c!=h){for(var a=0;a<x.length;a++)x[a][0]==c[1]&&x[a][1]==d&&x.splice(a,1);y()}})}function y(){chrome.extension.sendRequest({reqtype:"set-hiddenthreads",hiddenthreads:x})}
function z(d,c){var a=p.createElement("div"),b="qr"+Math.floor(Math.random()*1E3);a.id=b;a.style.borderTop="0px none";a.style.borderBottom="1px solid #CCCCCC";a.style.borderLeft="1px solid #CCCCCC";a.style.borderRight="1px solid #CCCCCC";a.innerHTML='<span title="'+chrome.i18n.getMessage("close")+'" style="float: right;cursor: pointer;font-weight: bold;font-size: 1.1em;padding: 1px;" id="close'+b+'">&nbsp;X&nbsp;</span><div style="text-align: center;cursor: move;padding: 1px;margin-bottom: 10px;" class="postblock">'+
chrome.i18n.getMessage("quick_reply")+" (#"+d+")</div>"+A;if(B)a.innerHTML+='<iframe id="'+b+'iframe" src="about:blank" style="display: none;min-width:100px;height:50px;margin:0px;padding:0px;"></iframe>';a.className="reply";a.style.margin="0";a.style.padding="0";a.style.position="absolute";for(var e=c.offsetLeft,f=c.offsetTop,i=c;i.offsetParent;)if(i==p.getElementsByTagName("body")[0])break;else{e+=i.offsetParent.offsetLeft;f+=i.offsetParent.offsetTop;i=i.offsetParent}a.style.left=e;a.style.top=
f;e=a.getElementsByTagName("table");for(f=0;f<e.length;f++)e[f].width=="100%"&&e[f].parentNode.removeChild(e[f]);e=a.getElementsByTagName("div");for(f=0;f<e.length;f++)e[f].className!="postblock"&&e[f].id!="recaptcha_area"&&e[f].id!="recaptcha_image"&&e[f].innerHTML.indexOf("recaptcha")==-1&&e[f].parentNode.removeChild(e[f]);e=a.getElementsByTagName("tr");for(f=0;f<e.length;f++)e[f].innerHTML=='<td></td><td colspan="2">\n</td>'&&e[f].parentNode.removeChild(e[f]);if(B){a.getElementsByTagName("form")[0].id=
b+"form";if(a.getElementsByTagName("form")[0].action.search("#")!=-1)a.getElementsByTagName("form")[0].action=a.getElementsByTagName("form")[0].action.split("#")[0];e=a.getElementsByTagName("input");for(f=0;f<e.length;f++)if(e[f].value=="Submit"){e[f].setAttribute("submitted","false");e[f].setAttribute("qrbid",b);e[f].addEventListener("click",function(){p.getElementById(this.getAttribute("qrbid")+"iframe").style.display="block";p.getElementById(this.getAttribute("qrbid")+"form").submit()},j)}a.getElementsByTagName("form")[0].setAttribute("target",
b+"iframe")}n(a,c);firstinput=a.getElementsByTagName("input")[0];e=p.createElement("input");e.name="resto";e.value=d;e.type="hidden";n(e,firstinput);C(a);qrbclose=p.getElementById("close"+b);qrbclose.setAttribute("qrbid",b);qrbclose.addEventListener("click",function(){var k=this.getAttribute("qrbid");k=p.getElementById(k);k.parentNode.removeChild(k)},j);return a}
function D(d,c){if(E||F||G){d||(d=p);for(var a=d.getElementsByTagName("a"),b=0;b<a.length;b++){var e=h,f=c,i=a[b].href.match(/.*quote\(\'([0-9]+)\'\)/i);if(i!=h){e=i[1];if(!f){i=u.match(/.*\/res\/([0-9]+).*/i);if(i!=h)f=i[1]}if(a[b].textContent.search("X")!=-1)a[b].textContent=e}else if(a[b].className=="quotejs"){i=a[b].href.match(/[.*]?res\/([0-9]+)(?:\.html)?\#q([0-9]+)/i);if(i!=h){f=i[1];e=i[2];if(a[b].textContent.search("X")!=-1)a[b].textContent=e}}if(E&&e&&f&&a[b].href!="javascript:return false;"){a[b].setAttribute("postID",
e);a[b].setAttribute("threadID",f);a[b].setAttribute("thisElement",a[b]);a[b].setAttribute("isQuickReply","true");E&&a[b].addEventListener("click",function(){var k=this.getAttribute("threadID"),m=this.getAttribute("postID");qrb=z(k,this.parentNode);k=qrb.getElementsByTagName("textarea");for(var l=0;l<k.length;l++)k[l].value=k[l].value!=""?">>"+m+"\n\n"+k[l].value:">>"+m+"\n"},j);a[b].href="javascript:false;"}if(F&&e&&a[b].getAttribute("processed")==h){if(f=p.location.href.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i)){i=
p.createElement("a");i.href="javascript:void(reppop('http://sys.4chan.org/"+f[1]+"/imgboard.php?mode=report&no="+e+"'));";i.style.textDecoration="none";i.innerHTML=' <img border="0" src="'+chrome.extension.getURL("images/button_report.png")+'" title="'+chrome.i18n.getMessage("report_post")+'">';n(i,a[b])}a[b].setAttribute("processed","true")}if(G&&a[b].href.toLowerCase()=="mailto:sage"&&a[b].getAttribute("processed")==h){a[b].innerHTML="&nbsp;"+a[b].innerHTML+"&nbsp;";a[b].style.textDecoration="none";
a[b].style.background="url('"+chrome.extension.getURL("images/sage.png")+"')";a[b].style.backgroundRepeat="repeat";a[b].setAttribute("processed","true")}}}}
function H(d){if(fa){var c=d.href.match(/.*images\.4chan\.org\/.*\/src\/(.*)/i);if(c==h)c=d.href.match(/.*4chanarchive\.org\/images\/(.*)/i);if(c==h)c=d.href.match(/.*inb4\.im\/.*\/src\/(.*)/i);if(c)if(d.innerHTML.substring(0,4)=="<img"){if(d.getAttribute("expanded")==h){d.setAttribute("expanded","false");d.setAttribute("expandImage",expandImage);d.setAttribute("expandOriginalHTML",d.innerHTML);d.setAttribute("onClick","javascript:return false;");img=d.getElementsByTagName("img")[0];d.setAttribute("thumbSRC",
img.getAttribute("src"));d.setAttribute("thumbWidth",img.getAttribute("width"));d.setAttribute("thumbHeight",img.getAttribute("height"));d.target="_self";d.addEventListener("click",function(a){if(a.which==2)w.open(this.getAttribute("expandImage"),"_blank");else if(a.which==1)if(this.getAttribute("expanded")!="true"){this.innerHTML='<img style="border: 0px none;min-width: '+this.getAttribute("thumbWidth")+"px;min-height: "+this.getAttribute("thumbHeight")+'px;" src="'+this.getAttribute("expandImage")+
'" border="0" align="left" hspace="20">';this.setAttribute("expanded","true")}else{this.innerHTML=this.getAttribute("expandOriginalHTML");this.setAttribute("expanded","false")}},j);if(ga){c=p.createEvent("MouseEvents");c.initMouseEvent("click",g,g,w,0,0,0,0,0,j,j,j,j,0,h);d.dispatchEvent(c)}}}else expandImage=d.href}}
function I(d,c){for(var a=d.getElementsByTagName("a"),b=0;b<a.length;b++){var e=a[b].href.match(/.*\/[0-9]+(?:\.html)?#([0-9]+)/i);if(e==h)e=a[b].href.match(/\#([0-9]+)/i);if(e!=h)if(a[b].innerHTML=="No."){d.setAttribute("postID",e[1]);d.className="4c4c_reply"}else{if(ha&&a[b].getAttribute("refID")==h)if(a[b].innerHTML.match(/^\&gt\;\&gt\;[0-9]+/i)!=h){a[b].setAttribute("refID",e[1]);a[b].addEventListener("mousemove",function(f){var i=p.getElementById("ref"+this.getAttribute("refID"));if(!i){i=p.createElement("div");
i.id="ref"+this.getAttribute("refID");i.className="reply";i.style.margin="0";i.style.padding="0";i.style.position="absolute";for(var k=u.search("4chan.org")==-1?p.getElementsByTagName("table"):p.getElementsByClassName("4c4c_reply"),m=0;m<k.length;m++){var l=k[m].getAttribute("postID");if(l&&l==this.getAttribute("refID")){i.innerHTML=k[m].innerHTML;if(k[m].getAttribute("op")=="true"){i.className="postblock";i.innerHTML='<div style="position: absolute;right: 0px;top: 0px;font-size: 1.5em;margin: 0px;padding: 1px;" class="unkfunc">OP</div>'+
i.innerHTML}}}n(i,this)}i.style.left=f.clientX+p.body.scrollLeft+p.documentElement.scrollLeft+25;i.style.top=f.clientY+p.body.scrollTop+p.documentElement.scrollTop+10},j);a[b].addEventListener("mouseout",function(){var f=p.getElementById("ref"+this.getAttribute("refID"));f&&f.parentNode.removeChild(f)},j)}}else c&&H(a[b])}}
function ia(d,c,a,b,e,f,i){i||(i=[]);if(f&&f.length>0){var k=f.shift();if(k.width!="100%"&&k.d!="0"&&k.align!="right")d.innerHTML+="<table>"+k.innerHTML+"</table>"}if(f&&f.length>0)setTimeout(ia,1,d,c,a,b,e,f,i);else{c.style.display="none";c=p.getElementsByClassName("4c4c_reply");for(f=0;f<c.length;f++)if(c[f].getAttribute("threadID")==a)c[f].style.display="none";c=d.getElementsByTagName("table");for(f=0;f<c.length;f++)I(c[f],g);D(d,a);c=p.getElementsByTagName("span");for(f=0;f<c.length;f++)c[f].id==
"omittedposts"+a&&n(d,c[f]);b.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_retract.png")+'" title="'+chrome.i18n.getMessage("retract")+'">&nbsp;';e.innerHTML=chrome.i18n.getMessage("thread_expanded",a)}}
function C(d){d||(d=p);for(var c=d.getElementsByTagName("input"),a=0;a<c.length;a++)if(c[a].name=="name"){if(J!="")c[a].value=J}else if(c[a].name=="email"){if(K!="")c[a].value=K}else if(c[a].name=="sub"){if(L!="")c[a].value=L}else if(c[a].name=="pwd")if(M!="")c[a].value=M;c=d.getElementsByTagName("textarea");for(a=0;a<c.length;a++)if(c[a].name=="com")if(c[a].value==""&&N!="")c[a].value=N}
function ja(d,c){var a=j;if(d&&d.length>0){a=d.shift();if(a.getAttribute("special")!=h||a.getAttribute("postID")>O.getAttribute("postID")){D(a);n(a,O);O=a;P=O.getAttribute("postID")}}if(d&&d.length>0)setTimeout(ja,10,d,c);else Q=c}
function na(){var d=j,c=u.match(/.*\/res\/([0-9]+).*/i);if(c!=h)d=c[1];if(d){var a=new XMLHttpRequest;a.open("HEAD",T+"res/"+d,g);a.send();a.a=d;a.onreadystatechange=function(){if(a.readyState==4)if(Q&&(a.status==404||a.getResponseHeader("Last-Modified")!=Q)){var b=new XMLHttpRequest;b.open("GET",T+"res/"+a.a,g);b.send();b.a=a.a;b.onreadystatechange=function(){var e=[];e.length=0;if(b.status==404){if(p.forms[1].getAttribute("has404d")=="false"){p.forms[1].setAttribute("has404d","true");var f=p.createElement("span");
f.setAttribute("special","true");f.innerHTML=chrome.i18n.getMessage("thread_404");f.style.color="red";f.style.fontSize="2.0em";e.push(f)}}else if(b.status==200){f=p.createElement("span");f.innerHTML=b.responseText;f=f.getElementsByTagName("table");for(var i=0;i<f.length;i++){I(f[i],g);f[i].getAttribute("postID")!=h&&f[i].getAttribute("postID")>P&&e.push(f[i])}}if(e.length>0){Q=j;f=b.getResponseHeader("Last-Modified");if(!O){i=p.forms[1].getElementsByClassName("4c4c_reply");for(var k=0;k<i.length;k++)if(i[k].getAttribute("postID")!=
h&&i[k].getAttribute("op")==h){O=i[k];P=O.getAttribute("postID")}}O||(O=p.forms[1].getElementsByTagName("blockquote")[0]);ja(e,f)}}}};p.forms[1].getAttribute("has404d")=="false"&&setTimeout(na,1E4)}}var A,U=h,O=j,P=0,u,T,Q=h,oa=j,ga=j,E=h,B=h,pa=h,fa=h,ha=h,V=h,qa=h,ra=h,G=h,F=h,W=h,X=h,q=h,x=h,J=h,K=h,L=h,N=h,M=h,Y=j;if(typeof gBrowser!="undefined")Y=g;
function sa(d){if(p.forms.length>0){var c=j;if(!d){d=p;c=g;if(W&&w.location.href.search("4chan.org")!=-1){var a=p.createElement("div");a.id="threadwatcher";a.style.borderTop="0px none";a.style.borderBottom="1px solid #CCCCCC";a.style.borderLeft="1px solid #CCCCCC";a.style.borderRight="1px solid #CCCCCC";a.innerHTML='<span title="'+chrome.i18n.getMessage("refresh")+'" style="float: right;cursor: pointer;font-weight: bold;font-size: 1.1em;padding: 1px;" id="refreshthreadwatcher">&nbsp;R&nbsp;</span><div style="text-align: center;cursor: move;padding: 1px;margin-bottom: 0px;" class="postblock">'+
chrome.i18n.getMessage("watched_threads")+'</div><table cellpadding="1" cellspacing="0" id="watchboxtable" style="margin: 3px;"></table>';a.className="reply";a.style.margin="0";a.style.padding="0";a.style.position="absolute";a.style.left="10";a.style.top="25";n(a,p.getElementsByTagName("table")[0]);s();p.getElementById("refreshthreadwatcher").addEventListener("click",function(){ca()},j)}}var b=d.getElementsByTagName("a");for(a=0;a<b.length;a++)if(b[a].innerHTML=="Reply"&&E){var e=b[a].href.match(/.*\/([0-9]+)(?:\.html)?/i);
if(e!=h){e=e[1];var f=p.createElement("a");f.href="javascript:false;";f.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_quickreply.png")+'" title="'+chrome.i18n.getMessage("quick_reply")+'">';f.setAttribute("onclick","return false;");f.setAttribute("threadID",e);f.addEventListener("click",function(){for(var m=d.getElementsByTagName("input"),l=0;l<m.length;l++)m[l].name.search(this.getAttribute("threadID"))!=-1&&z(this.getAttribute("threadID"),m[l])},j);b[a].parentNode.innerHTML+=
'<span id="spacer'+e+'">&nbsp;</span>';var i=d.getElementById("spacer"+e);n(f,i)}}else if(b[a].innerHTML=="No."){e=b[a].href.match(/.*\/([0-9]+)(?:\.html)?\#([0-9]+)/i);if(e!=h)if(e[1]==e[2])b[a].name=e[1]}else H(b[a]);U=Y?p.forms[1]:p.forms.delform?p.forms[1]:p.body;if(c&&U){if(qa){e=w.location.href.match(/(^.*)\/res\/[0-9]+.*/i);if(e==h)e=w.location.href.match(/(^.*)\//i);if(e!=h)p.forms[0].action+="#return="+encodeURI(e[1])}b=p.getElementsByTagName("div");for(a=0;a<b.length;a++)if(b[a].className==
"postarea"){A=b[a].innerHTML;C(p)}c=U.childNodes;f="thread"+Math.floor(Math.random()*1E3);var k=h;if(W)k=p.createElement("a");O=e=lastnode=h;for(a=0;a<c.length;a++){node=c[a];if(node.nodeName.toLowerCase()!="hr"){if(!node.setAttribute){b=p.createElement("span");n(b,node);b.appendChild(node);node=b}node.setAttribute("hidethread",f)}if(!e&&node.nodeName.toLowerCase()=="input"&&node.type=="checkbox"){e=node.name;if(W){k.id="watch"+e;k.style.textDecoration="none";k.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_watch.png")+
'" title="'+chrome.i18n.getMessage("watch_thread")+'"> ';k.href="#";k.setAttribute("onClick","javascript:return false;");k.setAttribute("threadID",e);k.addEventListener("click",function(){var m=u.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(m!=h){var l=this.getAttribute("postsubject");if(l=="")l="&nbsp;";var v=this.getAttribute("postname");if(v=="")v="&nbsp;";m=[m[1],this.getAttribute("threadID"),l,v,""];aa(m)}},j);n(k,node)}if(X){b=p.createElement("a");b.id="threadhider"+e;b.style.textDecoration=
"none";b.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_retract.png")+'" title="'+chrome.i18n.getMessage("hide_thread")+'"> ';b.href="#";b.setAttribute("onClick","javascript:return false;");b.setAttribute("threadID",e);b.setAttribute("hidethreadID",f);b.addEventListener("click",function(){da(this.getAttribute("threadID"));for(var m=o("hidethread",this.getAttribute("hidethreadID"),j),l=0;l<m.length;l++)m[l].style.display="none";p.getElementById("unhide"+this.getAttribute("hidethreadID")).style.display=
"block"},j);n(b,node)}}if(W&&node.className)if(node.className.toLowerCase()=="filetitle")k.setAttribute("postsubject",node.textContent);else node.className.toLowerCase()=="postername"&&k.setAttribute("postname",node.textContent);if(node.nodeName.toLowerCase()=="table"&&!node.getAttribute("align")){if(u.search("4chan.org")==-1){b=node.getElementsByTagName("input");for(i=0;i<b.length;i++)b[i].type=="checkbox"&&node.setAttribute("postID",b[i].name)}node.setAttribute("threadID",e);D(node,e);I(node);O=
node;P=node.getAttribute("postID")}if(node.className&&node.className.toLowerCase()=="omittedposts"&&pa){b=p.createElement("a");b.style.textDecoration="none";b.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_expand.png")+'" title="'+chrome.i18n.getMessage("expand_thread")+'">&nbsp;';b.href="#";b.setAttribute("onClick","javascript:return false;");b.setAttribute("threadID",e);node.innerHTML='<span id="spacer2'+e+'"></span><span id="omittedposts'+e+'">'+node.innerHTML+"</span>";
i=p.getElementById("spacer2"+e);i.parentNode.insertBefore(b,i);node.setAttribute("threadID",e);b.setAttribute("threadID",e);b.setAttribute("expanded","false");b.addEventListener("click",function(){var m=p.getElementById("omittedposts"+this.getAttribute("threadID"));if(this.getAttribute("expanded")=="true"){p.getElementById("replies"+this.getAttribute("threadID")).parentNode.removeChild(p.getElementById("replies"+this.getAttribute("threadID")));this.innerHTML=this.getAttribute("retracthtml");m.innerHTML=
chrome.i18n.getMessage("thread_retracted",this.getAttribute("threadID"))+'<br clear="left">';this.setAttribute("expanded","false")}else{this.setAttribute("retracthtml",this.innerHTML);m.innerHTML=chrome.i18n.getMessage("thread_expanding",this.getAttribute("threadID"));this.style.textDecoration="none";this.style.color="#000000";this.style.fontWeight="bold";this.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_expandwait.png")+'">&nbsp;';var l=new XMLHttpRequest;l.open("GET",
T+"res/"+this.getAttribute("threadID"),g);l.send();l.a=this.getAttribute("threadID");l.c=this;l.b=m;l.onreadystatechange=function(){if(l.readyState==4)if(l.status==200){this.c.setAttribute("expanded","true");var v=p.createElement("span"),R=p.createElement("span");R.innerHTML=l.responseText;for(var ka=this.a,wa=this.c,xa=this.b,la=R.getElementsByTagName("form")[1].getElementsByTagName("table"),ma=[],S=0;S<la.length;S++)ma.push(la[S]);v.id="replies"+ka;ia(v,R,ka,wa,xa,ma)}else if(l.status==404)this.b.innerHTML=
chrome.i18n.getMessage("thread_404")}}},j)}if(node.nodeName.toLowerCase()=="hr"&&lastnode&&lastnode.nodeName.toLowerCase()=="br"){if(X){b=p.createElement("span");b.innerHTML='<a href="#" id="triggerunhide'+f+'"><img border="0" src="'+chrome.extension.getURL("images/button_expand.png")+'" title="'+chrome.i18n.getMessage("unhide_thread")+'"></a> '+chrome.i18n.getMessage("thread_is_hidden",e);b.id="unhide"+f;b.style.display="none";n(b,lastnode.previousSibling);b=p.getElementById("triggerunhide"+f);b.setAttribute("onClick",
"javascript:return false;");b.setAttribute("threadID",e);b.setAttribute("hidethreadID",f);b.addEventListener("click",function(){ea(this.getAttribute("threadID"));for(var m=o("hidethread",this.getAttribute("hidethreadID"),j),l=0;l<m.length;l++)m[l].style.display="block";p.getElementById("unhide"+this.getAttribute("hidethreadID")).style.display="none"},j)}e=h;f="thread"+Math.floor(Math.random()*1E3);k=p.createElement("a")}lastnode=node}b=U.innerHTML.split('<br clear="left"><hr>');if(!oa){for(a=0;a<
b.length;a++){e=b[a].match(/.*\<input type\=\"checkbox\" name\=\"([0-9]+)\".*/i);if(e!=h){c=p.createElement("table");c.innerHTML=b[a].split("</blockquote>")[0]+"</blockquote>";f=c.innerHTML.split("<hr>");if(f.length>0)c.innerHTML=f.pop();c.className="4c4c_reply";c.setAttribute("postID",e[1]);c.setAttribute("op","true");c.style.display="none";U.appendChild(c)}}oa=g}if(V){e=u.match(/.*\/res\/[0-9]+.*/i);if(e!=h)if(U.getAttribute("has404d")==h){U.setAttribute("has404d","false");setTimeout(na,1E4)}V=
j}D(d,h);if(X){e=u.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(e!=h)for(a=0;a<x.length;a++)if(x[a][0]==e[1])if(b=p.getElementById("threadhider"+x[a][1])){c=p.createEvent("MouseEvents");c.initMouseEvent("click",g,g,w,0,0,0,0,0,j,j,j,j,0,h);b.dispatchEvent(c)}}if(ra){e=u.match(/.*\/res\/[0-9]+.*/i);if(u.search("4chan.org")!=-1&&e&&O){a=p.createElement("table");a.className="reply";a.style.marginTop="1em";a.innerHTML='<tr onclick="self.scrollTo(0,0);" style="cursor: hand;"><td align="left" style="font-size: 2em;">&#x25B2;</td><td align="center" width="100%" style="font-size: 2em;">'+
chrome.i18n.getMessage("return_to_top")+'</td><td align="right" style="font-size: 2em;">&#x25B2;</td></tr>';n(a,O)}}}}}var Z=j,ta,ua,$;function va(d){if(Z){$.style.left=tx+d.clientX-ta;$.style.top=ty+d.clientY-ua;return j}}
function ya(d){for(var c=d.target;c.tagName.toLowerCase()!="html"&&!(c.className=="postblock"&&c.style.textAlign=="center");)c=c.parentNode;if(c.className=="postblock"&&c.style.textAlign=="center"){Z=g;$=c.parentNode;tx=parseInt($.style.left+0,10);ty=parseInt($.style.top+0,10);ta=d.clientX;ua=d.clientY;p.onmousemove=va;return j}}
function za(){p.addEventListener("mousedown",ya,j);p.addEventListener("mouseup",function(){Z=j},j);Q=p.lastModified;if(p.forms.length==0){var d=w.location.href.match(/http\:\/\/.*\.4chan\.org\/.*\#return\=(.*)/i);if(d!=h)if(p.body.innerHTML.search("<!-- thread:")>-1&&p.body.innerHTML.search("<!-- thread:")<500){var c=p.body.innerHTML.match(/\.*<\!-- thread\:([0-9]+),no\:([0-9]+) --\>.*/i);if(c!=h){if(c[1]==0)c[1]=c[2];w.location=decodeURI(d[1])+"/res/"+c[1]+"#"+c[2]}}}c=j;u=w.location.href;d=u.match(/.*\/\/([0-9a-zA-Z]+)\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);
if(d!=h){if(d[1]=="sys"||d[1]=="dis"||d[2]=="f")c=g;T="http://"+d[1]+".4chan.org/"+d[2]+"/"}if(!c){chrome.extension.sendRequest({reqtype:"get-options"},function(a){E=a.quickreply;B=a.quickreplyiframe;pa=a.expand;fa=a.expandimages;ha=a.preview;V=a.fetchreplies;qa=a.autonoko;G=a.sage;F=a.report;W=a.threadwatcher;X=a.hidethreads;ra=a.returntotop;q=a.watchedthreads;x=a.hiddenthreads;J=a.default_name;K=a.default_email;L=a.default_subject;N=a.default_comment;M=a.default_password;sa()});chrome.extension.onRequest.addListener(function(a){if(a.reqtype==
"expandall"){ga=g;a=p.getElementsByTagName("a");for(var b=0;b<a.length;b++)if(a[b].getAttribute("expanded")!=h)if(a[b].getAttribute("expanded")=="false"){var e=p.createEvent("MouseEvents");e.initMouseEvent("click",g,g,w,0,0,0,0,0,j,j,j,j,0,h);a[b].dispatchEvent(e)}}else if(a.reqtype=="visiturl")w.location.href=a.url})}}
if(Y){var w=h,p=h,Aa=function(d){if(d.originalTarget instanceof HTMLDocument){w=d.originalTarget.defaultView;p=d.originalTarget;w.location.href.match(/.*\/\/([0-9a-zA-Z]+)\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i)!=h&&za()}};window.addEventListener("load",function(){gBrowser.addEventListener("DOMContentLoaded",Aa,g)},j)}else{p=document;w=window;za()};
