function insertAfter(b,c){c.parentNode.insertBefore(b,c.nextSibling)}function watchThread(b){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(c){watchedthreads=c;for(var c=!1,a=0;a<watchedthreads.length;a++)watchedthreads[a][0]==b[0]&&watchedthreads[a][1]==b[1]&&(c=!0);c?alert(chrome.i18n.getMessage("thread_already_watched",b[1])):(watchedthreads.push(b),storeWatchedThreads(),alert(chrome.i18n.getMessage("thread_now_watched",b[1])));refreshThreadWatcher()})}
function unwatchThread(b,c){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(a){watchedthreads=a;for(a=0;a<watchedthreads.length;a++)watchedthreads[a][0]==b&&watchedthreads[a][1]==c&&watchedthreads.splice(a,1);storeWatchedThreads();refreshThreadWatcher()})}function storeWatchedThreads(){chrome.extension.sendRequest({reqtype:"set-watchedthreads",watchedthreads:watchedthreads})}
function updateWatchedThreadNote(b,c,a){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(f){watchedthreads=f;for(f=0;f<watchedthreads.length;f++)watchedthreads[f][0]==c&&watchedthreads[f][1]==a&&(watchedthreads[f][4]=b.replace('"',"").replace("<","").replace(">",""));storeWatchedThreads()})}function refreshThreadWatcherCache(){chrome.extension.sendRequest({reqtype:"get-watchedthreads"},function(b){watchedthreads=b;refreshThreadWatcher()})}
function refreshThreadWatcher(){var b=full_url.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(b!=null){var c=b[1];watchboxtable=document.getElementById("watchboxtable");watchboxtable.innerHTML='<tr><td class="postblock" style="border-right: 0px none;">No.</td><td class="postblock" style="border-left: 0px none;border-right: 0px none;">'+chrome.i18n.getMessage("subject")+'</td><td class="postblock" style="border-left: 0px none;border-right: 0px none;">'+chrome.i18n.getMessage("author")+'</td><td class="postblock" style="border-left: 0px none;border-right: 0px none;">'+
chrome.i18n.getMessage("note")+'</td><td class="postblock" style="border-left: 0px none;">&nbsp;</td></tr>';for(var b=[],a=0;a<watchedthreads.length;a++)watchedthreads[a][0]==c&&b.push(watchedthreads[a]);if(b.length==0)c=document.createElement("tr"),c.innerHTML='<td colspan="5" align="center">'+chrome.i18n.getMessage("no_watched_threads")+"</td>",watchboxtable.appendChild(c);else for(a=0;a<b.length;a++)c=document.createElement("tr"),c.innerHTML='<td style="padding-left: 3px;padding-right: 3px;">'+
b[a][1]+'</td><td class="filetitle" style="padding-left: 3px;padding-right: 3px;">'+b[a][2]+'</td><td class="postername" style="padding-left: 3px;padding-right: 3px;">'+b[a][3]+'</td><td style="padding-left: 3px;padding-right: 3px;"><input type="text" placeholder="'+chrome.i18n.getMessage("enter_a_note")+'" size="12" value="'+b[a][4]+'" id="note'+b[a][0]+b[a][1]+'"></td><td style="padding-left: 3px;padding-right: 3px;"><small>[<a href="/'+b[a][0]+"/res/"+b[a][1]+'">'+chrome.i18n.getMessage("view")+
'</a>] [<a href="#" id="delete'+b[a][0]+b[a][1]+'">'+chrome.i18n.getMessage("delete")+"</a>]</small></td>",watchboxtable.appendChild(c),c=document.getElementById("note"+b[a][0]+b[a][1]),c.setAttribute("board",b[a][0]),c.setAttribute("threadid",b[a][1]),c.onchange=function(){updateWatchedThreadNote(this.value,$(this).attr("board"),$(this).attr("threadid"))},c.onkeyup=function(){updateWatchedThreadNote(this.value,$(this).attr("board"),$(this).attr("threadid"))},c=document.getElementById("delete"+b[a][0]+
b[a][1]),c.setAttribute("board",b[a][0]),c.setAttribute("threadid",b[a][1]),c.addEventListener("click",function(){window.confirm(chrome.i18n.getMessage("stop_watching_thread",$(this).attr("threadid")))&&unwatchThread($(this).attr("board"),$(this).attr("threadid"))},!1)}}
function hideThread(b){chrome.extension.sendRequest({reqtype:"get-hiddenthreads"},function(c){hiddenthreads=c;c=full_url.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(c!=null){for(var a=!1,f=0;f<hiddenthreads.length;f++)hiddenthreads[f][0]==c[1]&&hiddenthreads[f][1]==b&&(a=!0);a||(hiddenthreads.push([c[1],b]),storeHiddenThreads())}})}
function unhideThread(b){chrome.extension.sendRequest({reqtype:"get-hiddenthreads"},function(c){hiddenthreads=c;c=full_url.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(c!=null){for(var a=0;a<hiddenthreads.length;a++)hiddenthreads[a][0]==c[1]&&hiddenthreads[a][1]==b&&hiddenthreads.splice(a,1);storeHiddenThreads()}})}function storeHiddenThreads(){chrome.extension.sendRequest({reqtype:"set-hiddenthreads",hiddenthreads:hiddenthreads})}
function checkQuickReplyBoxSubmitted(b){document.getElementById(b).getElementsByTagName("iframe")[0].src.search("Updating page.")!=-1?closeQuickReplyBox(b):setTimeout(checkQuickReplyBoxSubmitted,200,b)}function closeQuickReplyBox(b){b=document.getElementById(b);b.parentNode.removeChild(b)}
function quickReplyBox(b,c){var a=document.createElement("div"),f="qr"+Math.floor(Math.random()*1E3);a.id=f;a.style.borderTop="0px none";a.style.borderBottom="1px solid #CCCCCC";a.style.borderLeft="1px solid #CCCCCC";a.style.borderRight="1px solid #CCCCCC";a.innerHTML='<span title="'+chrome.i18n.getMessage("close")+'" style="float: right;cursor: pointer;font-weight: bold;font-size: 1.1em;padding: 1px;" id="close'+f+'">&nbsp;X&nbsp;</span><div style="text-align: center;cursor: move;padding: 1px;margin-bottom: 10px;" class="postblock">'+
chrome.i18n.getMessage("quick_reply")+" (#"+b+")</div>"+postarea;enable_quickreplyiframe&&(a.innerHTML+='<iframe id="'+f+'iframe" src="about:blank" style="display: none;min-width:100px;height:50px;margin:0px;padding:0px;"></iframe>');a.className="reply";a.style.margin="0";a.style.padding="0";a.style.position="absolute";for(var d=c.offsetLeft,e=c.offsetTop,g=c;g.offsetParent;)if(g==document.getElementsByTagName("body")[0])break;else d+=g.offsetParent.offsetLeft,e+=g.offsetParent.offsetTop,g=g.offsetParent;
a.style.left=d;a.style.top=e;d=a.getElementsByTagName("table");for(e=0;e<d.length;e++)d[e].width=="100%"&&d[e].parentNode.removeChild(d[e]);d=a.getElementsByTagName("div");for(e=0;e<d.length;e++)d[e].className!="postblock"&&d[e].id!="recaptcha_area"&&d[e].id!="recaptcha_image"&&d[e].innerHTML.indexOf("recaptcha")==-1&&d[e].parentNode.removeChild(d[e]);d=a.getElementsByTagName("tr");for(e=0;e<d.length;e++)d[e].innerHTML=='<td></td><td colspan="2">\n</td>'&&d[e].parentNode.removeChild(d[e]);if(enable_quickreplyiframe){a.getElementsByTagName("form")[0].id=
f+"form";if(a.getElementsByTagName("form")[0].action.search("#")!=-1)a.getElementsByTagName("form")[0].action=a.getElementsByTagName("form")[0].action.split("#")[0];d=a.getElementsByTagName("input");for(e=0;e<d.length;e++)d[e].value=="Submit"&&(d[e].setAttribute("submitted","false"),d[e].setAttribute("qrbid",f),d[e].addEventListener("click",function(){document.getElementById($(this).attr("qrbid")+"iframe").css("display","block");document.getElementById($(this).attr("qrbid")+"form").submit()},!1));
a.getElementsByTagName("form")[0].setAttribute("target",f+"iframe")}insertAfter(a,c);firstinput=a.getElementsByTagName("input")[0];d=document.createElement("input");d.name="resto";d.value=b;d.type="hidden";insertAfter(d,firstinput);autoFillPostBox(a);qrbclose=document.getElementById("close"+f);qrbclose.setAttribute("qrbid",f);qrbclose.addEventListener("click",function(){closeQuickReplyBox($(this).attr("qrbid"))},!1);return a}
function quickReplyQuote(b,c,a){qrb=quickReplyBox(b,a);b=qrb.getElementsByTagName("textarea");for(a=0;a<b.length;a++)b[a].value=b[a].value!=""?">>"+c+"\n\n"+b[a].value:">>"+c+"\n"}
function replaceRefLinksWithQuickReply(b,c){if(enable_quickreply||enable_report||enable_sage)b||(b=document),$("a",b).each(function(){var a=null,b=c,d=null;$(this).attr("href")&&(d=$(this).attr("href").match(/.*quote\(\'([0-9]+)\'\)/i));d!=null?(a=d[1],b||(d=full_url.match(/.*\/res\/([0-9]+).*/i),d!=null&&(b=d[1])),$(this).text().search("X")!=-1&&$(this).text(a)):$(this).hasClass("quotejs")&&(d=$(this).attr("href").match(/[.*]?res\/([0-9]+)(?:\.html)?\#q([0-9]+)/i),d!=null&&(b=d[1],a=d[2],$(this).text().search("X")!=
-1&&$(this).text(a)));enable_quickreply&&a&&b&&$(this).attr("href")!="javascript:return false;"&&($(this).attr("postID",a).attr("threadID",b).attr("thisElement",this),enable_quickreply&&$(this).attr("isQuickReply")!="true"&&($(this).attr("isQuickReply","true"),$(this).click(function(){quickReplyQuote($(this).attr("threadID"),$(this).attr("postID"),this.parentNode);return!1})));if(enable_report&&a&&$(this).attr("processed")==null){if(b=document.location.href.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i))d=
document.createElement("a"),d.href="javascript:void(reppop('http://sys.4chan.org/"+b[1]+"/imgboard.php?mode=report&no="+a+"'));",d.style.textDecoration="none",d.innerHTML=' <img border="0" src="'+chrome.extension.getURL("images/button_report.png")+'" title="'+chrome.i18n.getMessage("report_post")+'">',insertAfter(d,$(this));$(this).attr("processed","true")}enable_sage&&$(this).attr("href")&&$(this).attr("href").toLowerCase()=="mailto:sage"&&$(this).attr("processed")==null&&$(this).html("&nbsp;"+$(this).html()+
"&nbsp;").css("textDecoration","none").css("background-image","url('"+chrome.extension.getURL("images/sage.png")+"')").css("backgroundRepeat","repeat").attr("processed","true")})}
function setExpandImageAttributes(b){if(enable_expandimages){var c=b.href.match(/.*images\.4chan\.org\/.*\/src\/(.*)/i);c==null&&(c=b.href.match(/.*4chanarchive\.org\/images\/(.*)/i));c==null&&(c=b.href.match(/.*inb4\.im\/.*\/src\/(.*)/i));if(c)b.innerHTML.substring(0,4)=="<img"?$(b).attr("expanded")==void 0&&(img=$("img",b).first(),$(b).attr("expanded","false").attr("expandImage",expandImage).attr("expandOriginalHTML",$(b).html()).attr("thumbSRC",img.attr("src")).attr("thumbWidth",img.attr("width")).attr("thumbHeight",
img.attr("height")),$(b).click(function(a){if(a.which==2)window.open($(this).attr("expandImage"),"_blank");else if(a.which==1||a.which==void 0)$(this).attr("expanded")!="true"?($(this).html('<img style="border: 0px none;min-width: '+$(this).attr("thumbWidth")+"px;min-height: "+$(this).attr("thumbHeight")+'px;" src="'+$(this).attr("expandImage")+'" border="0" align="left" hspace="20">'),$(this).attr("expanded","true")):($(this).html($(this).attr("expandOriginalHTML")),$(this).attr("expanded","false"));
return!1}),expand_all_thumbs&&$(b).click()):expandImage=b.href}}
function setPostAttributes(b,c){$("a",b).each(function(){var a=null;$(this).attr("href")&&(a=$(this).attr("href").match(/.*\/[0-9]+(?:\.html)?#([0-9]+)/i));a==null&&$(this).attr("href")&&(a=$(this).attr("href").match(/\#([0-9]+)/i));a!=null?$(this).html()=="No."?$(b).attr("postID",a[1]).addClass("4c4c_reply"):enable_preview&&$(this).attr("refID")==void 0&&$(this).html().match(/^\&gt\;\&gt\;[0-9]+/i)!=null&&($(this).attr("refID",a[1]),$(this).bind("mousemove",function(a){var b=document.getElementById("ref"+
$(this).attr("refID"));if(!b){b=document.createElement("div");b.id="ref"+$(this).attr("refID");b.className="reply";b.style.margin="0";b.style.padding="0";b.style.position="absolute";var c=$((is_4chan?".4c4c_reply":"table")+'[postID="'+$(this).attr("refID")+'"]').first();c&&($(b).html(c.html()),c.attr("op")=="true"&&($(b).addClass("postblock"),$(b).html('<div style="position: absolute;right: 0px;top: 0px;font-size: 1.5em;margin: 0px;padding: 1px;" class="unkfunc">OP</div>'+$(b).html())));insertAfter(b,
this)}$(b).css("left",a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft+25).css("top",a.clientY+document.body.scrollTop+document.documentElement.scrollTop+10)}),$(this).bind("mouseout",function(){$("#ref"+$(this).attr("refID")).remove()})):c&&setExpandImageAttributes(this)})}
function processExpandTables(b,c,a,f,d,e,g){g||(g=[]);if(e&&e.length>0){var h=e.shift();h.width!="100%"&&h.cellpadding!="0"&&h.align!="right"&&(b.innerHTML+="<table>"+h.innerHTML+"</table>")}e&&e.length>0?setTimeout(processExpandTables,1,b,c,a,f,d,e,g):processExpandTablesFinish(b,c,a,f,d,g)}
function processExpandTablesFinish(b,c,a,f,d){c.getElementsByTagName("form");c.style.display="none";$('.4c4c_reply[threadID="'+a+'"]').hide();$("table",b).each(function(){setPostAttributes(this,!0)});replaceRefLinksWithQuickReply(b,a);$('span[id^="omittedposts"]').each(function(){this.id=="omittedposts"+a&&insertAfter(b,this)});$(f).html('<img border="0" src="'+chrome.extension.getURL("images/button_retract.png")+'" title="'+chrome.i18n.getMessage("retract")+'">&nbsp;');$(d).html(chrome.i18n.getMessage("thread_expanded",
a))}function processExpand(b,c,a,f,d){var e=[];$("table",$(c.getElementsByTagName("form")[1])).each(function(){e.push(this)});b.id="replies"+a;processExpandTables(b,c,a,f,d,e)}
function autoFillPostBox(b){b||(b=doc);for(var c=b.getElementsByTagName("input"),a=0;a<c.length;a++)if(c[a].name=="name"){if(default_name!="")c[a].value=default_name}else if(c[a].name=="email"){if(default_email!="")c[a].value=default_email}else if(c[a].name=="sub"){if(default_subject!="")c[a].value=default_subject}else if(c[a].name=="pwd"&&default_password!="")c[a].value=default_password;c=b.getElementsByTagName("textarea");for(a=0;a<c.length;a++)if(c[a].name=="com"&&c[a].value==""&&default_comment!=
"")c[a].value=default_comment}function processLatestRepliesLoop(b){var c=!1;if(b&&b.length>0&&(c=b.shift(),c.getAttribute("special")!=null||c.getAttribute("postID")>lastreply.getAttribute("postID")))replaceRefLinksWithQuickReply(c),insertAfter(c,lastreply),lastreply=c,lastreplyid=lastreply.getAttribute("postID");b&&b.length>0&&setTimeout(processLatestRepliesLoop,10,b)}
function processFetchedReplies(b){lastreply||$(".4c4c_reply",document.forms[1]).each(function(){$(this).attr("postID")&&$(this).attr("op")==void 0&&(lastreply=this,lastreplyid=$(this).attr("postID"))});lastreply||(lastreply=$("blockquote",document.forms[1]).first());processLatestRepliesLoop(b)}
function fetchLatestPosts(){var b=!1,c=full_url.match(/.*\/res\/([0-9]+).*/i);c!=null&&(b=c[1]);b&&($.ajax({url:base_url+"res/"+b,ifModified:!0,success:function(a){var b=[],c=document.createElement("span");c.innerHTML=a;$("table",c).each(function(){setPostAttributes(this,!0);$(this).attr("postID")>lastreplyid&&b.push(this)});processFetchedReplies(b)},statusCode:{404:function(){if($(document.forms[1]).attr("has404d")=="false"){var b=[];$(document.forms[1]).attr("has404d","true");var c=document.createElement("span");
$(c).attr("special","true").css("color","red").css("fontSize","2.0em").html(chrome.i18n.getMessage("thread_404"));b.push(c);processFetchedReplies(b)}}}}),$(document.forms[1]).attr("has404d")=="false"&&setTimeout(fetchLatestPosts,1E4))}function float4c4cMenu(){var b=$(document).scrollTop(),b=menu_position+b;$(window).height()<$4c4c_menu.height()?$4c4c_menu.css("top",menu_position):$4c4c_menu.stop().animate({top:b},500)}
var postarea,threads=[],lastreply=!1,lastreplyid=0,full_url,base_url,is_4chan=!1,$4c4c_menu,menu_position,last_modified=null,created_op_preview=!1,expand_all_thumbs=!1,enable_quickreply=null,enable_quickreplyiframe=null,enable_expand=null,enable_expandimages=null,enable_preview=null,enable_fetchreplies=null,enable_autonoko=null,enable_returntotop=null,enable_quickbrowse=null,enable_sage=null,enable_report=null,enable_threadwatcher=null,enable_hidethreads=null,enable_menu=null,watchedthreads=null,
hiddenthreads=null,default_name=null,default_email=null,default_subject=null,default_comment=null,default_password=null,delform=document.forms.delform?document.forms[1]:document.body;
function init4chan4chrome(b){if(document.forms.length>0){var c=!1;if(!b){b=document;c=!0;if(enable_threadwatcher&&is_4chan){var a=document.createElement("div");a.id="threadwatcher";a.style.borderTop="0px none";a.style.borderBottom="1px solid #CCCCCC";a.style.borderLeft="1px solid #CCCCCC";a.style.borderRight="1px solid #CCCCCC";a.innerHTML='<span title="'+chrome.i18n.getMessage("refresh")+'" style="float: right;cursor: pointer;font-weight: bold;font-size: 1.1em;padding: 1px;" id="refreshthreadwatcher">&nbsp;R&nbsp;</span><div style="text-align: center;cursor: move;padding: 1px;margin-bottom: 0px;" class="postblock">'+
chrome.i18n.getMessage("watched_threads")+'</div><table cellpadding="1" cellspacing="0" id="watchboxtable" style="margin: 3px;"></table>';a.className="reply";a.style.margin="0";a.style.padding="0";a.style.position="absolute";a.style.left="10";a.style.top="25";insertAfter(a,document.getElementsByTagName("table")[0]);refreshThreadWatcher();document.getElementById("refreshthreadwatcher").addEventListener("click",function(){refreshThreadWatcherCache()},!1)}if(enable_menu)$4c4c_menu=$(document.createElement("div")),
$4c4c_menu.attr("id","4c4cmenu").css("position","absolute").css("top","150px").css("right","0px").css("z-index","9999").css("text-align","center").css("font-size","1.25em").css("border-top-left-radius","5px 5px").css("border-bottom-left-radius","5px 5px").css("padding","7px").addClass("postblock").html('<a href="#" title="'+chrome.i18n.getMessage("return_to_top")+'" id="menu_top" class="quotejs">Top</a><br><a href="#" title="'+chrome.i18n.getMessage("expand_all_thumbnails")+'" id="menu_expand" class="quotejs">Expand</a><br><a href="#" title="'+
chrome.i18n.getMessage("browse_new_threads")+'" id="menu_return" class="quotejs">Browse</a>').appendTo("body"),menu_position=$4c4c_menu.position().top,float4c4cMenu(),$("#menu_top").css("text-decoration","none").click(function(){$("html, body").animate({scrollTop:0},0);return!1}),$("#menu_expand").css("text-decoration","none").click(function(){expand_all_thumbs=!0;$('a[expandImage][expanded="false"]').each(function(){$(this).click()});return!1}),$("#menu_return").css("text-decoration","none").click(function(){var b=
window.location.href.match(/http\:\/\/(.*)\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(b!=null)window.location="http://"+b[1]+".4chan.org/"+b[2]+"/?browse";return!1}),$(window).scroll(function(){float4c4cMenu()})}scrolltotopthread=!1;a=window.location.href.match(/http\:\/\/.*\.4chan\.org\/.*\?browse/i);enable_quickbrowse&&a!=null&&(scrolltotopthread=!0);$("a",b).each(function(){if($(this).html()=="Reply"&&enable_quickreply){var a=null;$(this).attr("href")&&(a=$(this).attr("href").match(/.*\/([0-9]+)(?:\.html)?/i));
if(a!=null){var c=a[1],a=document.createElement("a");a.href="javascript:false;";a.innerHTML='<img border="0" src="'+chrome.extension.getURL("images/button_quickreply.png")+'" title="'+chrome.i18n.getMessage("quick_reply")+'">';a.setAttribute("onclick","return false;");a.setAttribute("threadID",c);a.addEventListener("click",function(){for(var a=b.getElementsByTagName("input"),c=0;c<a.length;c++)a[c].name.search($(this).attr("threadID"))!=-1&&quickReplyBox($(this).attr("threadID"),a[c])},!1);this.parentNode.innerHTML+=
'<span id="spacer'+c+'">&nbsp;</span>';c=b.getElementById("spacer"+c);insertAfter(a,c)}}else $(this).html()=="No."?(a=null,$(this).attr("href")&&(a=$(this).attr("href").match(/.*\/([0-9]+)(?:\.html)?\#([0-9]+)/i)),a!=null&&a[1]==a[2]&&$(this).attr("name",a[1])):setExpandImageAttributes(this)});if(c&&delform){enable_autonoko&&(a=window.location.href.match(/(^.*)\/res\/[0-9]+.*/i),a==null&&(a=window.location.href.match(/(^.*)\//i)),a!=null&&(document.forms[0].action+="#return="+encodeURI(a[1])));postarea=
$(".postarea").first().html();autoFillPostBox(document);var a=delform.childNodes,f="thread"+Math.floor(Math.random()*1E3),d=null;enable_threadwatcher&&(d=document.createElement("a"));lastreply=threadID=lastnode=null;topthread=!1;lasthr=null;for(c=0;c<a.length;c++){node=a[c];var e=$(node);if(node.nodeName.toLowerCase()!="hr"){if(!node.setAttribute){var g=document.createElement("span");insertAfter(g,node);g.appendChild(node);node=g}node.setAttribute("hidethread",f)}topthread||(topthread=node,scrolltotopthread&&
window.scrollTo(0,topthread.offsetTop));if(!threadID&&node.nodeName.toLowerCase()=="input"&&node.type=="checkbox")threadID=node.name,enable_threadwatcher&&($(d).attr("id","watch"+threadID).attr("threadID",threadID).attr("href","#").css("textDecoration","none").html('<img border="0" src="'+chrome.extension.getURL("images/button_watch.png")+'" title="'+chrome.i18n.getMessage("watch_thread")+'"> '),$(d).click(function(){var a=full_url.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);if(a!=null){var b=$(this).attr("postsubject");
b==""&&(b="&nbsp;");var c=$(this).attr("postname");c==""&&(c="&nbsp;");a=[a[1],$(this).attr("threadID"),b,c,""];watchThread(a)}return!1}),insertAfter(d,node)),enable_hidethreads&&(g=document.createElement("a"),$(g).attr("id","threadhider"+threadID).attr("href","#").attr("threadID",threadID).attr("hidethreadID",f).css("textDecoration","none").html('<img border="0" src="'+chrome.extension.getURL("images/button_retract.png")+'" title="'+chrome.i18n.getMessage("hide_thread")+'"> '),$(g).click(function(){hideThread($(this).attr("threadID"));
$('[hidethread="'+$(this).attr("hidethreadID")+'"]').hide();$("#unhide"+$(this).attr("hidethreadID")).show();return!1}),insertAfter(g,node));enable_threadwatcher&&e.hasClass("filetitle")?$(d).attr("postsubject",e.text()):enable_threadwatcher&&e.hasClass("postername")&&$(d).attr("postname",e.text());node.nodeName.toLowerCase()=="table"&&!e.attr("align")&&(is_4chan&&$("input[type=checkbox]",node).each(function(){e.attr("postID",this.name)}),lastreplyid=e.attr("threadID",threadID).attr("postID"),replaceRefLinksWithQuickReply(node,
threadID),setPostAttributes(node),lastreply=node);if(enable_expand&&e.hasClass("omittedposts")){g=document.createElement("a");$(g).attr("href","#").attr("threadID",threadID).attr("expanded","false").css("textDecoration","none").html('<img border="0" src="'+chrome.extension.getURL("images/button_expand.png")+'" title="'+chrome.i18n.getMessage("expand_thread")+'">&nbsp;');e.attr("threadID",threadID).html('<span id="spacer2'+threadID+'"></span><span id="omittedposts'+threadID+'">'+node.innerHTML+"</span>");
var h=document.getElementById("spacer2"+threadID);h.parentNode.insertBefore(g,h);$(g).click(function(){var a=$("#omittedposts"+$(this).attr("threadID"));if($(this).attr("expanded")=="true")$("#replies"+$(this).attr("threadID")).remove(),$(this).html($(this).attr("retracthtml")),a.html(chrome.i18n.getMessage("thread_retracted",$(this).attr("threadID"))+'<br clear="left">'),$(this).attr("expanded","false");else{$(this).attr("retracthtml",$(this).html());a.html(chrome.i18n.getMessage("thread_expanding",
$(this).attr("threadID")));this.style.textDecoration="none";this.style.color="#000000";this.style.fontWeight="bold";$(this).html('<img border="0" src="'+chrome.extension.getURL("images/button_expandwait.png")+'">&nbsp;');var b=new XMLHttpRequest;b.open("GET",base_url+"res/"+$(this).attr("threadID"),!0);b.send();b.threadID=$(this).attr("threadID");b.spacer=this;b.omittedposts=a;b.onreadystatechange=function(){if(b.readyState==4)if(b.status==200){$(this.spacer).attr("expanded","true");var a=document.createElement("span"),
c=document.createElement("span");c.innerHTML=b.responseText;processExpand(a,c,this.threadID,this.spacer,this.omittedposts)}else b.status==404&&$(this.omittedposts).html(chrome.i18n.getMessage("thread_404"))}}return!1})}enable_quickbrowse&&e.hasClass("pages")&&($("a",node).each(function(){this.href+="?browse"}),$("form",node).each(function(){this.action+="?browse"}));if(node.nodeName.toLowerCase()=="hr"&&lastnode&&lastnode.nodeName.toLowerCase()=="br"){if(enable_hidethreads)d=document.createElement("span"),
d.innerHTML='<a href="#" id="triggerunhide'+f+'"><img border="0" src="'+chrome.extension.getURL("images/button_expand.png")+'" title="'+chrome.i18n.getMessage("unhide_thread")+'"></a> '+chrome.i18n.getMessage("thread_is_hidden",threadID),d.id="unhide"+f,d.style.display="none",insertAfter(d,lastnode.previousSibling),d=document.getElementById("triggerunhide"+f),$(d).attr("threadID",threadID).attr("hidethreadID",f),$(d).click(function(){unhideThread($(this).attr("threadID"));$('[hidethread="'+$(this).attr("hidethreadID")+
'"]').show();$("#unhide"+$(this).attr("hidethreadID")).hide();return!1});lasthr=node;threadID=null;f="thread"+Math.floor(Math.random()*1E3);d=document.createElement("a")}lastnode=node}if(!created_op_preview){f=delform.innerHTML.split('<br clear="left"><hr>');for(c=0;c<f.length;c++)a=f[c].match(/.*\<input type\=\"checkbox\" name\=\"([0-9]+)\".*/i),a!=null&&(d=document.createElement("table"),$(d).html(f[c].split("</blockquote>")[0]+"</blockquote>").attr("postID",a[1]).attr("op","true").addClass("4c4c_reply").css("display",
"none").appendTo(delform),a=$(d).html().split("<hr>"),a.length>0&&$(d).html(a.pop()));created_op_preview=!0}enable_fetchreplies&&(a=full_url.match(/.*\/res\/[0-9]+.*/i),a!=null&&$(delform).attr("has404d")==void 0&&($(delform).attr("has404d","false"),setTimeout(fetchLatestPosts,1E4)),enable_fetchreplies=!1);replaceRefLinksWithQuickReply(b,null);if(enable_hidethreads&&(a=full_url.match(/.*\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i),a!=null))for(c=0;c<hiddenthreads.length;c++)hiddenthreads[c][0]==a[1]&&$("#threadhider"+
hiddenthreads[c][1]).click();if(enable_returntotop&&is_4chan&&(a=full_url.match(/.*\/res\/[0-9]+.*/i)))c=document.createElement("table"),c.className="reply",c.style.clear="both",c.innerHTML='<tr onclick="self.scrollTo(0,0);" style="cursor: hand;"><td align="left" style="font-size: 2em;">&#x25B2;</td><td align="center" width="100%" style="font-size: 2em;">'+chrome.i18n.getMessage("return_to_top")+'</td><td align="right" style="font-size: 2em;">&#x25B2;</td></tr>',insertAfter(c,lasthr);if(enable_quickbrowse&&
is_4chan&&(a=window.location.href.match(/(^.*)\/res\/[0-9]+.*/i),a==null))c=document.createElement("table"),c.className="reply",c.style.clear="both",c.innerHTML='<tr style="cursor: hand;"><td align="left" style="font-size: 2em;">&#x25B2;</td><td align="center" width="100%" style="font-size: 2em;">'+chrome.i18n.getMessage("browse_new_threads")+'</td><td align="right" style="font-size: 2em;">&#x25B2;</td></tr>',c.addEventListener("click",function(){var a=window.location.href.match(/http\:\/\/(.*)\.4chan\.org\/(.*)\/.*/i);
if(a!=null)window.location="http://"+a[1]+".4chan.org/"+a[2]+"/?browse"},!1),insertAfter(c,lasthr)}}}var isdrag=!1,x,y,dobj;function movemouse(b){if(isdrag)return dobj.style.left=tx+b.clientX-x,dobj.style.top=ty+b.clientY-y,!1}
function selectmouse(b){for(var c=b.target;c.tagName.toLowerCase()!="html"&&!(c.className=="postblock"&&c.style.textAlign=="center");)c=c.parentNode;if(c.className=="postblock"&&c.style.textAlign=="center")return isdrag=!0,dobj=c.parentNode,tx=parseInt(dobj.style.left+0,10),ty=parseInt(dobj.style.top+0,10),x=b.clientX,y=b.clientY,document.onmousemove=movemouse,!1}document.addEventListener("mousedown",selectmouse,!1);document.addEventListener("mouseup",function(){isdrag=!1},!1);last_modified=document.lastModified;
if(document.forms.length==0){var m=window.location.href.match(/http\:\/\/.*\.4chan\.org\/.*\#return\=(.*)/i);if(m!=null&&document.body.innerHTML.search("<\!-- thread:")>-1&&document.body.innerHTML.search("<\!-- thread:")<500){var m2=document.body.innerHTML.match(/\.*<\!-- thread\:([0-9]+),no\:([0-9]+) --\>.*/i);if(m2!=null)m2[1]==0&&(m2[1]=m2[2]),window.location=decodeURI(m[1])+"/res/"+m2[1]+"#"+m2[2]}}var disable4c4c=!1;full_url=document.location.href;m=full_url.match(/.*\/\/([0-9a-zA-Z]+)\.4chan\.org\/([0-9a-zA-Z]+)\/.*/i);
if(m!=null){is_4chan=!0;if(m[1]=="sys"||m[1]=="dis"||m[2]=="f")disable4c4c=!0;base_url="http://"+m[1]+".4chan.org/"+m[2]+"/"}
disable4c4c||(chrome.extension.sendRequest({reqtype:"get-options"},function(b){enable_quickreply=b.quickreply;enable_quickreplyiframe=b.quickreplyiframe;enable_expand=b.expand;enable_expandimages=b.expandimages;enable_preview=b.preview;enable_fetchreplies=b.fetchreplies;enable_autonoko=b.autonoko;enable_sage=b.sage;enable_report=b.report;enable_threadwatcher=b.threadwatcher;enable_hidethreads=b.hidethreads;enable_menu=b.menu;enable_returntotop=b.returntotop;enable_quickbrowse=b.quickbrowse;watchedthreads=
b.watchedthreads;hiddenthreads=b.hiddenthreads;default_name=b.default_name;default_email=b.default_email;default_subject=b.default_subject;default_comment=b.default_comment;default_password=b.default_password;init4chan4chrome()}),chrome.extension.onRequest.addListener(function(b){if(b.reqtype=="expandall")expand_all_thumbs=!0,$('a[expandImage][expanded="false"]').each(function(){$(this).click()});else if(b.reqtype=="visiturl")document.location.href=b.url}));
